name: Download IaC for Appstack
description: Download IaC for an appstack

inputs:
  appstack_uuid:
    description: 'UUID of the appstack to download'
    required: true
  output:
    description: 'File destination for zipped IaC code'
    required: false
    default: './iac'
  latest:
    description: 'Download IaC of the latest version of the specified appstack'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - appstack 
    - download-iac
    - --uuid
    - ${{ inputs.appstack_uuid }}
    - --output
    - ${{ inputs.output }}
    - --latest
    - ${{ inputs.latest }}
    - --log
    # based on ACTIONS_RUNNER_DEBUG, set to 2 for debug
    - ${{ inputs.enableDebug == 'true' && '2' || '3' }}
